services:
  postgres:
    image: 'postgres:14.5'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'game-review-admin'
      POSTGRES_PASSWORD: 'game-review'
      POSTGRES_DB: 'gamerave'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
