########## Games Entity ##########
GET http://localhost:3000/games
###
GET http://localhost:3000/games/1
###
POST http://localhost:3000/games
Content-Type: application/json

{
    "name":"Days Gone"
}
###
DELETE http://localhost:3000/games/1



########## Reviews Entity ##########
GET http://localhost:3000/reviews
###
GET http://localhost:3000/reviews/1
###
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "title":"Muito bom!",
    "description":"Tudo quadrado",
    "gameName":"Days Gone"
}
###
PUT http://localhost:3000/reviews/10
Content-Type: application/json

{
    "gameName":"Days Gone"
}
###
DELETE http://localhost:3000/reviews/9



########## Game Like And Game Dislike  ##########
POST http://localhost:3000/like/3
###
POST http://localhost:3000/dislike/2



########## Review Like And Review Dislike  ##########
POST http://localhost:3000/like-review/10
###
POST http://localhost:3000/dislike-review/10
